### ISSUE TITLE
preserveAspectRatio not found in svg

### ISSUE THREAD

**Issue by Jc2k** [hiltonm/dioxus-charts#2]
I get this with a fresh setup of dioxus and dioxus-charts:

```
304 |       cx.render(rsx! {
    |  _______________-
305 | |         div {
306 | |             svg {
307 | |                 xmlns: "http://www.w3.org/2000/svg",
...   |
310 | |                 class: "{cx.props.class_chart_bar}",
311 | |                 preserveAspectRatio: "xMidYMid meet",
    | |                -^^^^^^^^^^^^^^^^^^^ function or associated item not found in `svg`
    | |________________|
    | 
```

In bar, line and pie.

`preserve_aspect_ratio` works.

**Comment by hiltonm** [comment]
Yep, you are right, they changed that with version 0.3.2, and this was tested only with 0.3.1. I will need to update and publish another version for that, thanks of the heads up! Just in case you don't know, you can specify the dioxus full version on your Cargo.toml to lock it like its done at examples/demo/Cargo.toml. Since dioxus is still far from stable we can expect this to keep breaking with almost every release they make. Cheers!

**Comment by Jc2k** [comment]
Cheers!

(I'm actually running a pinned commit from the dev branch because I need to do something very specific with vdom, fully expect problems :))
